# debug settings in the app
app.streetcomplete.debug=false

# Kotlin
kotlin.daemon.jvmargs=-Xmx4096m

# Gradle
# 8 gigabytes as maximum because during the linking of a Kotlin/Native release (i.e. iOS), more than
# 4 gigabytes is necessary, otherwise the task will fail with "e: Compilation failed: Java heap
# space" quickly.
org.gradle.jvmargs=-Xmx8g -Dfile.encoding=UTF-8
org.gradle.configuration-cache=false
org.gradle.caching=true

# Android
android.enableJetifier=false
android.useAndroidX=true

# Build scripts
app.streetcomplete.POEditorAPIToken=invalid
app.streetcomplete.POEditorCookie=invalid
app.streetcomplete.POEditorPHPSESSID=invalid
app.streetcomplete.GithubApiToken=invalid
