import com.esotericsoftware.yamlbeans.YamlConfig
import com.esotericsoftware.yamlbeans.YamlWriter
import org.gradle.api.DefaultTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.TaskAction
import java.io.FileInputStream
import java.io.FileWriter
import java.io.StringWriter
import java.nio.charset.StandardCharsets

/** Counts the occurance of changes in git commits for a given regex and
 *  writes the result in a YML file. */
open class GitStatsTask : DefaultTask() {
    @get:Input lateinit var targetFile: String
    @get:Input lateinit var commitFileFilter: Regex
    @get:Input var commitSkipList: Array<String> = arrayOf()
  
    @TaskAction fun run() {
        val countsByName = mutableMapOf<String, Int>()
        val countsByCommit = mutableMapOf<String, Int>()
        Runtime.getRuntime().exec("git log --no-merges --pretty='%an'%n%H --numstat").inputStream.bufferedReader().useLines { lines ->
            var name = ""
            var commit = ""
            var commitNext = false
            var skipNext = false
            for(line in lines) {
                if (line.startsWith('\'')) {
                    name = line.trim('\'')
                    skipNext = false
                    commitNext = true
                } else if (commitNext) {
                    commit = line
                    if (line.trim() in commitSkipList) {
                      println("Found and skipping commit " + line)
                      skipNext = true
                    }
                    commitNext = false
                } else {
                    val splits = line.split(Regex("\\s+"))
                    val additions = splits[0].toIntOrNull() ?: continue
                    val deletions = splits[1].toIntOrNull() ?: continue
                    if (!splits.last().matches(commitFileFilter)) continue
                    val commitTotal = additions + deletions
                    if (!skipNext) {
                        countsByName[name] = commitTotal + countsByName.getOrPut(name, { 0 })
                    }
                    if (commitTotal > 400) {
                        countsByCommit[commit] = commitTotal
                    }
                }
            }
        }
        countsByCommit.entries.sortedByDescending { it.value }.forEach { println("${it.value}\t${it.key}") }
        println("*************************************************************")
        countsByName.entries.sortedByDescending { it.value }.forEach { println("${it.value}\t${it.key}") }
        println("*************************************************************")

        val config = YamlConfig().apply {
            writeConfig.setWriteClassname(YamlConfig.WriteClassName.NEVER)
            writeConfig.isFlowStyle = true
            writeConfig.setWrapColumn(Int.MAX_VALUE)
            writeConfig.setEscapeUnicode(false)
        }
        val fileWriter = FileWriter(targetFile, false)
        fileWriter.write("# Do not edit manually.\n")
        fileWriter.write("# Data generated by counting number of commits per person.\n\n")
        for ((property, value) in countsByName.entries.sortedByDescending { it.value }) {
            val str = StringWriter()
            val writer = YamlWriter(str, config)
            writer.write(value)
            writer.close()
            fileWriter.write("$property: $str")
        }
        fileWriter.close()
    }
}
