/*
* This quest was generated by the StreetComplete QuestCreator (https://github.com/ENT8R/StreetCompleteQuestCreator)
*/

package de.westnordost.streetcomplete.quests.tracktype;

import de.westnordost.streetcomplete.R;
import de.westnordost.streetcomplete.quests.ImageListQuestAnswerFragment;

public class AddTracktypeForm extends ImageListQuestAnswerFragment
{
    private final OsmItem[] TYPES = new OsmItem[] {
            new OsmItem("grade1", R.drawable.tracktype_grade1, R.string.quest_tracktype_grade1),
            new OsmItem("grade2", R.drawable.tracktype_grade2, R.string.quest_tracktype_grade2),
            new OsmItem("grade3", R.drawable.tracktype_grade3, R.string.quest_tracktype_grade3),
            new OsmItem("grade4", R.drawable.tracktype_grade4, R.string.quest_tracktype_grade4),
            new OsmItem("grade5", R.drawable.tracktype_grade5, R.string.quest_tracktype_grade5),
    };

    @Override protected OsmItem[] getItems() { return TYPES; }

    @Override protected int getItemsPerRow() { return 3; }
}
