/*
* This quest was generated by the StreetComplete QuestCreator (https://github.com/ENT8R/StreetCompleteQuestCreator)
*/

package de.westnordost.streetcomplete.quests.parking_fee;

import android.os.Bundle;
import android.support.annotation.NonNull;

import java.util.Map;

import javax.inject.Inject;

import de.westnordost.streetcomplete.R;
import de.westnordost.streetcomplete.data.osm.SimpleOverpassQuestType;
import de.westnordost.streetcomplete.data.osm.changes.StringMapChangesBuilder;
import de.westnordost.streetcomplete.data.osm.download.OverpassMapDataDao;
import de.westnordost.streetcomplete.quests.AbstractQuestAnswerFragment;

public class AddParkingFee extends SimpleOverpassQuestType
{
	@Inject public AddParkingFee(OverpassMapDataDao overpassServer) { super(overpassServer); }

	@Override protected String getTagFilters()
	{
		return "nodes, ways, relations with" +
		       " amenity = parking and !fee and !fee:conditional and" +
		       " access ~ yes|customers|public";
	}

	public AbstractQuestAnswerFragment createForm() { return new AddParkingFeeForm(); }

	public void applyAnswerTo(Bundle answer, StringMapChangesBuilder changes)
	{
		boolean hasFee = answer.getBoolean(AddParkingFeeForm.FEE);
		changes.add("fee", toYesNo(hasFee));

		if(answer.containsKey(AddParkingFeeForm.FEE_CONDITONAL_HOURS))
		{
			String hours = answer.getString(AddParkingFeeForm.FEE_CONDITONAL_HOURS);
			changes.add("fee:conditional", toYesNo(!hasFee) + " @ (" + hours + ")");
		}
	}

	@Override public String getCommitMessage() { return "Add whether there is a parking fee"; }
	@Override public int getIcon() { return R.drawable.ic_quest_parking_fee; }
	@Override public int getTitle(@NonNull Map<String, String> tags) { return R.string.quest_parking_fee_title; }

	private static String toYesNo(boolean b) {  return b ? "yes" : "no"; }
}
