package de.westnordost.streetcomplete.osm.places

import de.westnordost.osmfeatures.Feature
import de.westnordost.streetcomplete.data.osm.mapdata.Element
import de.westnordost.streetcomplete.osm.Tags
import de.westnordost.streetcomplete.osm.applyTo
import de.westnordost.streetcomplete.osm.featureId
import de.westnordost.streetcomplete.osm.isChildOf
import de.westnordost.streetcomplete.osm.localized_name.LocalizedName
import de.westnordost.streetcomplete.osm.removeCheckDates

/** Return whether the newly selected [newFeature] with [newNames] should replace or should not
 *  replace the [previousFeature] with [previousNames]. Returns null if it can not be ascertained
 *  with certainty. */
fun shouldReplacePlace(
    element: Element?,
    newFeature: Feature,
    newNames: List<LocalizedName>,
    previousFeature: Feature?,
    previousNames: List<LocalizedName>,
): Boolean? {
    val hasAddedNames = newNames.isNotEmpty() && newNames.containsAll(previousNames)
    val hasChangedNames = previousNames != newNames
    val hasChangedId = newFeature.id != previousFeature?.id
    val hasChangedFeatureId = previousFeature?.featureId != newFeature.featureId
    val isFeatureSubtype =
        previousFeature != null
        && (newFeature.isChildOf(previousFeature) || previousFeature.isChildOf(newFeature))
    val wasDisused = element != null && element.isDisusedPlace()
    val isDisused = newFeature.isDisusedPlace()
    val wasBrand =  previousFeature?.isSuggestion == true
    val isBrand =  newFeature.isSuggestion

    val shouldNotReplaceShop =
        // a brand preset was applied, but neither names nor feature type changed (see #5940)
        !hasChangedNames && !hasChangedFeatureId
        // name(s) were added but feature wasn't changed at all; user wouldn't be able to answer if
        // the place changed or not anyway, so rather keep previous information
        || hasAddedNames && !hasChangedId
        // place has been added, nothing to replace
        || element == null
    if (shouldNotReplaceShop) return false

    val shouldAlwaysReplaceShop =
        // the feature is or was a brand feature and the type has changed -> definitely different
        // place now; If the name and/or feature changed, the user might just have corrected the
        // spelling or corrected the type (e.g. kindergarten -> childcare), so it is better to ask.
        // Also, a place might have been tagged as fast food before and now it is pizza fast food,
        // this should not lead to auto-replacing (see #6406)
        (isBrand || wasBrand) && !isFeatureSubtype
        // was vacant before but not anymore (-> cleans up any previous tags that may be
        // associated with the old place)
        || wasDisused && hasChangedId
        // it's vacant now
        || isDisused

    if (shouldAlwaysReplaceShop) return true

    return null
}

/** Apply replacing a place feature to the given [tags]
 *  Removes any place-related tags before applying this feature to the given [tags]. */
fun Feature.applyReplacePlaceTo(tags: Tags) {
    removePlaceRelatedTags(tags)
    applyTo(tags)
}

/** Remove any tags that are related to places, e.g. when re-tagging on place into another, or
 *  marking it as vacant. */
fun removePlaceRelatedTags(tags: Tags) {
    tags.removeCheckDates()

    for (key in tags.keys.toList()) {
        if (KEYS_THAT_SHOULD_BE_REMOVED_WHEN_PLACE_IS_REPLACED.any { it.matches(key) }) {
            tags.remove(key)
        }
    }
}

// generated by "make update" from https://github.com/mnalis/StreetComplete-taginfo-categorize/
private val KEYS_THAT_SHOULD_BE_REMOVED_WHEN_PLACE_IS_REPLACED = listOf(
    "shop_?[1-9]?(:.*)?", "craft_?[1-9]?", "amenity_?[1-9]?", "club_?[1-9]?", "old_amenity",
    "old_shop", "information", "leisure", "office_?[1-9]?", "tourism",
    // popular shop=* / craft=* subkeys
    "marketplace", "household", "swimming_pool", "laundry", "golf", "sports", "ice_cream",
    "scooter", "music", "retail", "yes", "ticket", "newsagent", "lighting", "truck", "car_repair",
    "car_parts", "video", "fuel", "farm", "car", "tractor", "hgv", "ski", "sculptor",
    "hearing_aids", "surf", "photo", "boat", "gas", "kitchen", "anime", "builder", "hairdresser",
    "security", "bakery", "bakehouse", "fishing", "doors", "kiosk", "market", "bathroom", "lamps",
    "vacant", "insurance(:.*)?", "caravan", "gift", "bicycle", "bicycle_rental", "insulation",
    "communication", "mall", "model", "empty", "wood", "hunting", "motorcycle", "trailer",
    "camera", "water", "fireplace", "outdoor", "blacksmith", "electronics", "fan", "piercing",
    "stationery", "sensory_friendly(:.*)?", "street_vendor", "sells(:.*)?", "safety_equipment",
    "battery", "frame", "paint",
    // obsoleted information
    "(demolished|abandoned|disused)(:(?!bui).+)?", "was:.*", "not:.*", "damage", "created_by",
    "check_date", "opening_date", "last_checked", "checked_exists:date", "pharmacy_survey",
    "old_ref", "update", "import_uuid", "review", "fixme:atp",
    // classifications / links to external databases
    "fhrs:.*", "old_fhrs:.*", "fvst:.*", "ncat", "nat_ref", "gnis:.*", "winkelnummer",
    "type:FR:FINESS", "type:FR:APE", "kvl_hro:amenity", "ref:DK:cvr(:.*)?", "certifications?",
    "transiscope", "opendata:type", "local_ref", "official_ref", "ref:thw", "ref:nav",
    "ref:GR:kepId", "ref:bufa", "ref:walmart", "ref:rspo", "ref:cue", "ref:regon",
    "ref:BY:trade_register", "ref:vb", "ref:comfort", "ref:bademilj.", "ref:HU:vatin",
    "ref:HU:company", "ref:ico", "ref:scoutingnl", "ref:anlegg", "ref:FR:sport_equip",
    "ref:FR:RNA", "ref:FR:CRTA", "ref:charity",
    // names and identifications
    "name_?[1-9]?(:.*)?", ".*_name_?[1-9]?(:.*)?", "noname", "branch(:.*)?", "brand(:.*)?",
    "nobrand", "not:brand(:.*)?", "network(:.*)?", "operator(:.*)?", "operator_type", "ref",
    "ref:vatin(:.*)?", "designation", "SEP:CLAVEESC", "identifier", "ref:FR:SIRET", "ref:FR:SIREN",
    "ref:FR:NAF", "(old_)?ref:FR:prix-carburants", "ref:HU:(vatin|company|om|ntak)", "ref:UAI",
    "ref:edubase(:group)?", "ref:mise", "ref:FR:LaPoste", "ref:Hermes", "ref:pol_id", "ref:isil",
    "ref:INEP", "ref:coop", "ref:shop:num", "ref:norgesgruppen", "ref:rema", "ref:tobacco",
    "ref:mekonomen", "ref:google",
    // contacts
    "contact_person", "contact(:.*)?", "phone(:.*)?", "phone_?[1-9]?", "emergency:phone",
    "emergency_telephone_code",
    "mobile", "fax", "facebook", "instagram", "twitter", "youtube", "telegram", "tiktok", "email",
    "website_?[1-9]?(:.*)?", "app:.*", "ownership",
    "url", "url:official", "source_ref:url", "owner", "ref:website",
    // payments
    "payment(:.*)?", "payment_multi_fee", "currency(:.*)?", "cash_withdrawal(:.*)?", "fee",
    "charge", "charge_fee", "money_transfer", "donation:compensation", "paypoint",
    // generic shop/craft attributes
    "seasonal", "time", "opening_hours(:.*)?", "check_(in|out)", "wifi", "internet",
    "internet_access(:.*)?", "second_hand", "self_service", "automated", "license:.*",
    "bulk_purchase", ".*:covid19", "language:.*", "baby_feeding", "description(:.*)?",
    "description[0-9]", "min_age", "max_age", "supermarket(:.*)?", "social_facility(:.*)?",
    "functional", "trade", "wholesale", "sale", "smoking(:.*)?", "zero_waste", "origin",
    "attraction", "strapline", "dog", "showroom", "toilets?(:.*)?", "sanitary_dump_station",
    "changing_table(:.*)?", "wheelchair(.*)?", "blind", "company(:.*)?", "stroller", "walk-in",
    "webshop", "operational_status.*", "status", "drive_through", "surveillance(:.*)?",
    "outdoor_seating", "indoor_seating", "colour", "access_simple", "floor", "product_category",
    "guide", "source_url", "category", "kids_area", "kids_area:indoor", "resort", "since", "state",
    "temporary", "self_checkout", "audio_loop", "related_law(:.*)?", "official_status(:.*)?",
    // food and drink details
    "bar", "cafe", "coffee", "microroasting", "microbrewery", "brewery", "real_ale", "taproom",
    "training", "distillery", "drink(:.*)?", "cocktails", "alcohol", "wine([:_].*)?",
    "happy_hours", "diet:.*", "cuisine", "ethnic", "tasting", "breakfast", "lunch", "organic",
    "produced_on_site", "restaurant", "food", "pastry", "pastry_shop", "product", "produce",
    "chocolate", "fair_trade", "butcher", "reservation(:.*)?", "takeaway(:.*)?", "delivery(:.*)?",
    "caterer", "real_fire", "flour_fortified", "highchair", "fast_food", "pub", "snack",
    "confectionery", "drinking_water:refill",
    // related to repair shops/crafts
    "services?(:.*)?", "motorcycle:.*", "repair", ".*:repair", "electronics_repair(:.*)?",
    "workshop",
    // shop=hairdresser, shop=clothes
    "unisex", "male", "female", "gender", "gender_simple", "lgbtq(:.*)?", "gay", "female:signed",
    "male:signed",
    // healthcare
    "healthcare(:.*)?", "healthcare_.*", "health", "health_.*", "speciality", "medical_.*",
    "emergency_ward", "facility(:.*)?", "activities", "healthcare_facility(:.*)?",
    "laboratory(:.*)?", "blood(:.*)?", "blood_components", "infection(:.*)?", "disease(:.*)?",
    "covid19(:.*)?", "COVID_.*", "CovidVaccineCenterId", "coronaquarantine", "hospital(:.*)?",
    "hospital_type_id", "emergency_room", "sample_collection(:.*)?", "bed_count", "capacity:beds",
    "part_time_beds", "personnel:count", "staff_count(:.*)?", "admin_staff", "doctors",
    "doctors_num", "nurses_num", "counselling_type", "testing_centres", "toilets_number",
    "urgent_care", "vaccination", "clinic", "hospital", "pharmacy", "alternative", "laboratory",
    "sample_collection", "provided_for(:.*)?", "social_facility_for", "ambulance", "ward",
    "HSE_(code|hgid|hgroup|region)", "collection_centre", "design", "AUTORIZATIE", "reg_id",
    "post_addr", "scope", "ESTADO", "NIVSOCIO", "NO", "EMP_EST", "COD_HAB", "CLA_PERS", "CLA_PRES",
    "snis_code:.*", "hfac_bed", "hfac_type", "nature", "moph_code", "IJSN:.*", "massgis:id",
    "OGD-Stmk:.*", "paho:.*", "panchayath", "pbf_contract", "pcode", "pe:minsa:.*", "who:.*",
    "pharmacy:category", "tactile_paving", "HF_(ID|TYPE|N_EN)", "RoadConn", "bin", "hiv(:.*)?",
    "ref:ZonaSanitaria", "ref:cuie_codigo", "ref:sisa_(codigo|tipologia)", "ref:SUKL", "ref:sede",
    "ref:msal", "ref:(micro)?red", "ref:category", "ref:osakidetza", "ref:ogdsteiermark",
    "ref:luebeck", "ref:nmd", "ref:nhn", "ref:hvakostertannlegen", "ref:boots", "ref:apotek1",
    "ref:GB:nhs_ods", "ref:GB:cqc_location", "ref:FR:FINESS", "ref:FR:RPPS", "ref:fps_health(:.*)",
    "ref:doh", "ref:csioz", "ref:CNES",
    // accommodation & layout
    "rooms", "stars", "accommodation", "beds", "capacity(:persons)?", "laundry_service",
    "guest_house",
    // amenity=place_of_worship
    "deanery", "subject:(wikidata|wikipedia|wikimedia_commons)", "church", "church:type",
    // schools
    "capacity:(pupils|teachers)", "grades", "population:pupils(:.*)?",
    "school:(FR|gender|trust|type|type_idn|group:type|selective)", "primary",
    // clubs
    "animal(_breeding|_training)?", "billiards(:.*)?", "board_game", "sport_1", "sport:boating",
    "boat:type", "canoe(_rental|:service)?", "kayak(_rental|:service)?",
    "sailboat(_rental|:service)?", "horse_riding", "rugby", "boules", "callsign", "card_games",
    "car_service", "catastro:ref", "chess(:.*)?", "children", "climbing(:.*)?", "club(:.*)?",
    "communication(:amateur_radio.*)", "community_centre:for", "dffr:network", "dormitory",
    "education_for:ages", "electrified", "esperanto", "events_venue", "family", "federation",
    "free_flying(:.*)?", "freemasonry(:.*)?", "free_refill", "gaelic_games(:.*)?", "membership",
    "military_service", "model_aerodrome(:.*)?", "mode_of_organisation(:.*)?", "snowmobile",
    "social_centre(:for)?", "source_dat", "tennis", "old_website", "organisation", "school_type",
    "scout(:type)?", "fraternity", "live_music", "lockable", "playground(:theme)?", "nudism",
    "music_genre", "length", "fire_station:type:FR", "cadet", "observatory:type", "tower:type",
    "zoo", "shooting", "commons", "groomer", "group_only", "hazard", "identity", "interaction",
    "logo", "maxheight", "provides", "regional", "scale", "site", "plots", "allotments",
    "local_food", "monitoring:pedestrian", "recording:automated", "yacht", "background_music",
    "url:spaceapi", "openfire", "fraternity(:.*)?", "ref:DSV", "ref:FOS", "ref_fftt",
    // misc specific attributes
    "clothes", "shoes", "tailor", "beauty", "tobacco", "carpenter", "furniture", "lottery",
    "sport", "dispensing", "tailor:.*", "gambling", "material", "raw_material", "stonemason",
    "studio", "scuba_diving(:.*)?", "polling_station", "collector", "books", "agrarian",
    "musical_instrument", "massage", "parts", "post_office(:.*)?", "religion", "denomination",
    "rental", ".*:rental", "tickets:.*", "public_transport", "goods_supply", "pet", "appliance",
    "artwork_type", "charity", "company", "crop", "dry_cleaning", "factory", "feature",
    "air_conditioning", "atm", "vending", "vending_machine", "recycling_type", "museum",
    "license_classes", "dance:.*", "isced:level", "school", "preschool", "university",
    "research_institution", "research", "member_of", "topic", "townhall:type", "parish", "police",
    "government", "thw:(lv|rb|ltg)", "office", "administration", "administrative", "association",
    "transport", "utility", "consulting", "Commercial", "commercial", "private", "taxi",
    "admin_level", "official_status", "target", "liaison", "diplomatic(:.*)?", "embassy",
    "consulate", "aeroway", "department", "faculty", "aerospace:product", "boundary", "population",
    "diocese", "depot", "cargo", "function", "game", "party", "political_party.*",
    "telecom(munication)?", "service_times", "kitchen:facilities", "it:(type|sales)",
    "cannabis:cbd", "bath:type", "bath:(open_air|sand_bath)", "animal_boarding", "animal_shelter",
    "mattress", "screen", "monitoring:weather", "public", "theatre", "culture", "library",
    "cooperative(:.*)?", "winery", "curtain", "lawyer(:.*)?", "local_authority(:.*)?", "equipment",
    "hackerspace",
    "camp_site", "camping", "bbq", "static_caravans", "emergency(:.*)?", "evacuation_cent(er|re)",
    "education", "engineering", "forestry", "foundation", "lawyer", "logistics", "military",
    "community_centre", "bank", "operational", "users_(PLWD|boy|elderly|female|girl|men)",
    "Comments?", "comments?", "entrance:(width|step_count|kerb:height)", "fenced", "motor_vehicle",
    "shelter",
)
    .flatMap { listOf(it, "source:$it", "check_date:$it") }
    .map { it.toRegex() }
