package de.westnordost.streetcomplete.quests.orchard_produce

enum class OrchardProduce(val osmValue: String, val landuse: String? = null) {

    // may have been mistaken for an orchard (i.e. agave) from satellite imagery
    SISAL("sisal", "farmland"),
    GRAPE("grape", "vineyard"),

    AGAVE("agave"),
    ALMOND("almond"),
    APPLE("apple"),
    APRICOT("apricot"),
    ARECA_NUT("areca_nut"),
    AVOCADO("avocado"),
    BANANA("banana"),
    SWEET_PEPPER("sweet_pepper"),
    BLUEBERRY("blueberry"),
    BRAZIL_NUT("brazil_nut"),
    CACAO("cacao"),
    CASHEW("cashew"),
    CHERRY("cherry"),
    CHESTNUT("chestnut"),
    CHILLI_PEPPER("chilli_pepper"),
    COCONUT("coconut"),
    COFFEE("coffee"),
    CRANBERRY("cranberry"),
    DATE("date"),
    FIG("fig"),
    GRAPEFRUIT("grapefruit"),
    GUAVA("guava"),
    HAZELNUT("hazelnut"),
    HOP("hop"),
    JOJOBA("jojoba"),
    KIWI("kiwi"),
    KOLA_NUT("kola_nut"),
    LEMON("lemon"),
    LIME("lime"),
    MANGO("mango"),
    MANGOSTEEN("mangosteen"),
    MATE("mate"),
    NUTMEG("nutmeg"),
    OLIVE("olive"),
    ORANGE("orange"),
    PALM_OIL("palm_oil"),
    PAPAYA("papaya"),
    PEACH("peach"),
    PEAR("pear"),
    PEPPER("pepper"),
    PERSIMMON("persimmon"),
    PINEAPPLE("pineapple"),
    PISTACHIO("pistachio"),
    PLUM("plum"),
    RASPBERRY("raspberry"),
    RUBBER("rubber"),
    STRAWBERRY("strawberry"),
    TEA("tea"),
    TOMATO("tomato"),
    TUNG_NUT("tung_nut"),
    VANILLA("vanilla"),
    WALNUT("walnut"),
}
