/*
* This quest was generated by the StreetComplete QuestCreator (https://github.com/ENT8R/StreetCompleteQuestCreator)
*/

package de.westnordost.streetcomplete.quests.public_transport_bus_stop;

import android.os.Bundle;
import java.util.Map;

import javax.inject.Inject;

import de.westnordost.streetcomplete.R;
import de.westnordost.streetcomplete.data.osm.SimpleOverpassQuestType;
import de.westnordost.streetcomplete.data.osm.changes.StringMapChangesBuilder;
import de.westnordost.streetcomplete.data.osm.download.OverpassMapDataDao;
import de.westnordost.streetcomplete.quests.AbstractQuestAnswerFragment;

public class AddPublicTransportBusStop extends SimpleOverpassQuestType
{
    @Inject public AddPublicTransportBusStop(OverpassMapDataDao overpassServer) { super(overpassServer); }

    @Override
    protected String getTagFilters() { return "nodes with highway=bus_stop and !public_transport"; }

    public AbstractQuestAnswerFragment createForm() { return new AddPublicTransportBusStopForm(); }

    public void applyAnswerTo(Bundle bundle, StringMapChangesBuilder changes)
    {
        String answer = bundle.getString(AddPublicTransportBusStopForm.ANSWER);
        if (answer != null)
        {
            changes.add("public_transport", answer);
        }
    }

    @Override public String getCommitMessage() { return "Add public_transport tag on bus_stop"; }
    @Override public int getIcon() { return R.drawable.ic_quest_bus; }
    @Override public int getTitle(Map<String, String> tags) { return R.string.quest_public_transport_bus_stop_title; }
}
