/*
* This quest was generated by the StreetComplete QuestCreator (https://github.com/ENT8R/StreetCompleteQuestCreator)
*/

package de.westnordost.streetcomplete.quests.public_transport_bus_stop;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import de.westnordost.streetcomplete.R;
import de.westnordost.streetcomplete.quests.YesNoQuestAnswerFragment;

public class AddPublicTransportBusStopForm extends YesNoQuestAnswerFragment
{
	private static final String
			PLATFORM = "platform",
			STOP_POSITION = "stop_position";

	public static final String ANSWER = "answer";

	@Override
	public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
	{
		View view = super.onCreateView(inflater, container, savedInstanceState);
		View buttonPanel = setButtonsView(R.layout.quest_buttonpanel_public_transport_bus_stop);

		buttonPanel.findViewById(R.id.buttonPlatform).setOnClickListener(v -> onClickAnswer(PLATFORM));
		buttonPanel.findViewById(R.id.buttonStopPosition).setOnClickListener(v -> onClickAnswer(STOP_POSITION));
		return view;
	}

	protected void onClickAnswer(String answer)
	{
		Bundle bundle = new Bundle();
		bundle.putString(ANSWER, answer);
		applyImmediateAnswer(bundle);
	}
}
