= Documentation utilisateur de l'application android
:icons: font
:models: models
:experimental:
:incremental:
:numbered:
:toc: macro
:window: _blank
:correction!:

toc::[]

Date : 05/10/2025 +
Equipe : 1A-1 +
Client : Yahn Formanczak +
Projet : Street Complete +

== Description du projet

=== Équipe

L'équipe était composée de cinq membres avec les rôles suivants :

- *Hugo Thollon* : Scrum Master
- *Naria Savary* : Product Owner
- *Pablo Marquet* : Développeur
- *Raphaël Lamothe* : Développeur
- *Nicolas* : Développeur

=== Contexte du projet
Street Complete est une application Android ayant pour but d’améliorer la qualité des données d’Open Street Map avec des enquêtes sur le terrain. L’application fonctionne avec une partie de gamification et invite aux modifications sous forme de quêtes thématiques.

=== Objectifs du projet
Monter en compétence sur :
- Le modèle de données OSM
- Kotlin et Kotlin Multiplatform
- Android Studio et l’environnement mobile

Réaliser des contributions au projet open source StreetComplete :

- Ajout ou amélioration de quêtes simples
- Début de migration d’éléments de l’UI vers *Compose Multiplatform*
- Participation non-code : documentation, traduction, collecte de données

== Fonctionnement du projet 

=== Langage et plateforme
- Plateforme principale : Android, iOS (en cours)
- Langage de programmation : Kotlin

=== Cartographie
StreetComplete utilise MapLibre, une collection de cartes SDKs open-source pour du développement web et mobile.

=== Communication entre les serveurs OSM (OpenStreetMap)
- Téléchargement des données OSM via API officielle OpenStreetMap
- Upload des requêtes utilisateurs (ajout, modification et suppression des données OSM à l'aide de tags) dans la base OSM 

== Fonctionnalités 

=== Quêtes (« quests »)
- Les quêtes sont des questions ciblées sur des objets OSM manquants ou incomplets dans votre zone (route, bâtiment, équipement).
- Exemples de questions types : « Le trottoir existe-t-il ? », « Quel type de surface a cette route ? », « Ce parking à vélos est-il couvert ? », « Heures d’ouverture ? », etc. 

=== Overlays (couches d’affichage interactives)
Les overlays permettent de visualiser/éditer directement certains tags OSM :
- Éclairage des rues
- Trottoirs 
- Parking à vélos, voies cyclables  
- Stationnement rue 
- Adresses 
- Points d’intérêt / commerces, bâtiments
- Mobilier urbain 
- Type de bâtiment 

=== Suivi des contributions & gamification
- Lorsqu’une quête est terminée, l’utilisateur gagne des points, suivi de son positionnement national et global sur un leaderboard 
- Statistiques personnelles et comparatives motivent le contributeur néophyte à progresser

== Interface de l'application
A REMPLIR

== Support et Contact
Pour toute question ou assistance, veuillez contacter notre Product Owner à l'adresse suivante : naria.savary@etu.univ-tlse2.fr

== Conclusion
Nous espérons que cette documentation vous guidera dans votre utilisation de l'appli CompleteStreetMap.

